# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wallet.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cwallet.proto\"/\n\x0cTopupRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x02\"0\n\rDeductRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x02\"!\n\x0e\x42\x61lanceRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"M\n\x0eWalletResponse\x12\x0e\n\x06status\x18\x01 \x01(\x08\x12\x13\n\x0bnew_balance\x18\x02 \x01(\x02\x12\x16\n\x0etransaction_id\x18\x03 \x01(\t2\x93\x01\n\rWalletService\x12\'\n\x05Topup\x12\r.TopupRequest\x1a\x0f.WalletResponse\x12)\n\x06\x44\x65\x64uct\x12\x0e.DeductRequest\x1a\x0f.WalletResponse\x12.\n\nGetBalance\x12\x0f.BalanceRequest\x1a\x0f.WalletResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'wallet_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TOPUPREQUEST']._serialized_start=16
  _globals['_TOPUPREQUEST']._serialized_end=63
  _globals['_DEDUCTREQUEST']._serialized_start=65
  _globals['_DEDUCTREQUEST']._serialized_end=113
  _globals['_BALANCEREQUEST']._serialized_start=115
  _globals['_BALANCEREQUEST']._serialized_end=148
  _globals['_WALLETRESPONSE']._serialized_start=150
  _globals['_WALLETRESPONSE']._serialized_end=227
  _globals['_WALLETSERVICE']._serialized_start=230
  _globals['_WALLETSERVICE']._serialized_end=377
# @@protoc_insertion_point(module_scope)
